//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int IDDatPhong { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public string TrangThai { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public string Vetify { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> XuLiLuc { get; set; }
        public Nullable<int> NguoiXuLi { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
