//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu
    {
        public int IDGioiThieu { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string NoiDung { get; set; }
        public Nullable<byte> ThuTu { get; set; }
    }
}
