//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int IDSuKien { get; set; }
        public string AnhNen { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayToChuc { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
