//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaPhong
    {
        public int IDGiaPhong { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public string TenLoai { get; set; }
        public Nullable<decimal> GiaDem { get; set; }
        public Nullable<decimal> CuoiTuan { get; set; }
        public Nullable<decimal> Tuan { get; set; }
        public Nullable<decimal> Thang { get; set; }
        public Nullable<decimal> NgayLe { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
