//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagePhong
    {
        public int IDImageHome { get; set; }
        public Nullable<byte> Rank { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public string TieuDe { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
